version: "3.2"

networks:
  backbone:
    external:
      name: backbone

services:
  aws_localstack:
    build: .
    image: localstack:fix-timestamps
    networks:
      - backbone
    ports:
      - "4567-4593:4567-4593"
      - "8080:8080"
    environment:
      - SERVICES=${LOCALSTACK_SERVICES:-s3,s3api,dynamodb}
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack.plista.develop
      - START_WEB=1
      - DEBUG=1
      - VIRTUAL_HOST=localstack.plista.develop
      - VIRTUAL_PORT=8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - $PWD:/opt/code/localstack
